---
name: Build Pre-Release Packages for Linux (dev)
run-name: Building Pre-Release Packages for Linux (dev)
on:
  push:
    branches: dev
    paths-ignore: 
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
jobs:
  build-linux-releases:
    runs-on: ubuntu-latest
    container:
      image: eliaswf/jammy-chromedriver-python-r:latest
    outputs:
      upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
      tag_name:   ${{ steps.create_tag_name.outputs.tag_name }}
    steps:
    - name: Update Git to version 2.18 or higher
      run: |
        apt-get update
        apt-get install -y git

    - name: Checkout git repository on to Github Actions runner
      uses: actions/checkout@v3
      with:
        path: 'VisualizationTools'
        
    - name: Generate cache key using the number of the month (01 to 12)
      run: |
        date +%m
        echo "month_number=$(date +%m)" >> $GITHUB_ENV

    - name: check runner temp
      run: | 
        echo $RUNNER_TEMP

    - name: Temporarily change ownership for R site library path, so our cache can write to it during a restore
      run: | 
        chown -R $(whoami) /usr/local/lib/R/
        chown -R $(whoami) /usr/lib/R/

    - name: Cache the R site library to speed-up future workflow runs
      uses: actions/cache@v3
      id: cache-R-site-lib
      with:
        key: ${{ env.month_number }}
        path: |
          /usr/local/lib/R/site-library
          /usr/lib/R/site-library

    - name: Restore ownership for R site library path, after cache-write
      run: | 
        chown -R root /usr/local/lib/R/
        chown -R root /usr/lib/R/

    - name: Manually run R CMD Check from the shell
      continue-on-error: true
      working-directory: VisualizationTools
      run: R CMD check .

    # Build Linux binary package
    - name: Build platform-specific binary packages for the Analytic System
      working-directory: 'VisualizationTools'
      run: R CMD INSTALL -l ${{ runner.temp }} --build .

    # # Retrieve build artifact filenames
    - name: Retrieve package version from DESCRIPTION file and set as env variable
      working-directory: 'VisualizationTools'
      run: |
        echo "package_version=$(grep -oP '(?<=Version: )\d+\.\d+\.\d+' DESCRIPTION)" >> $GITHUB_ENV
        echo $(grep -oP '(?<=Version: )\d+\.\d+\.\d+' DESCRIPTION)

    - name: Retrieve binary package filename and set as env variable
      working-directory: 'VisualizationTools'
      run: | 
        echo "linux_binary_pkg_filename=$(ls VisualizationTools_${{ env.package_version }}_R_*.tar.gz)" >> $GITHUB_ENV
        echo $(ls VisualizationTools_${{ env.package_version }}_R_*.tar.gz)
        echo "linux_binary_pkg_filepath=$(realpath $(ls VisualizationTools_${{ env.package_version }}_R_*.tar.gz))" >> $GITHUB_ENV
        echo $(realpath $(ls VisualizationTools_${{ env.package_version }}_R_*.tar.gz))

    # Generate Release Metadata
    - name: Create autogenerated release tag name
      id: create_tag_name
      run: | 
        # Tag names follow a variant of the  SemVer 2.0.0 convention:
        # <major>.<minor>.<patch>-<pre-release>-build-<build>
        
        if [[ ${{ github.ref_name }} != "main" ]]; then
          # If the branch name is not main, we set a pre-release field in the SemVer
          echo "tag_name=${{ env.package_version }}-${{ github.ref_name }}-build-${{ github.run_number }}" >> "$GITHUB_ENV"
          echo "tag_name=${{ env.package_version }}-${{ github.ref_name }}-build-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
        else
          # Otherwise for main releases on "main", we omit the pre-release field.
          echo "tag_name=${{ env.package_version }}-build-${{ github.run_number }}" >> "$GITHUB_ENV"
          echo "tag_name=${{ env.package_version }}-build-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
        fi
        echo ${{ env.tag_name }}

    - name: Create Pre-release
      if: ${{ github.ref_name }} == "dev"
      id: create_prerelease
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag_name }}
        release_name: pre-release build for branch (${{ github.ref_name }}) on tag ${{ env.tag_name }}.
        body: |
          Automatic pre-release build for ${{ github.ref_name }} branch on tag ${{ env.tag_name }}.
        draft: false
        prerelease: true
    
    - name: Upload Linux Binary Package
      if: ${{ github.ref_name }} == "dev"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: ${{ env.linux_binary_pkg_filepath }}
        asset_name: Linux-binary-${{ env.linux_binary_pkg_filename }}
        asset_content_type: application/gzip
