---
name: R-CMD-check
run-name: Running R CMD check on VisualizationTools
on: 
  pull_request:
    types:
      - opened
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository on to Github Actions runner
      uses: actions/checkout@v3
    - name: Installs R using tidyverse r-lib Actions
      uses: r-lib/actions/setup-r@v2
    - name: Install R package dependencies using tidyverse r-lib Actions
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - name: Runs R CMD Check
      uses: r-lib/actions/check-r-package@v2
      with:
        error-on: '"error"'